import forms from "@tailwindcss/forms";

/**
 * Vegan Chef 디자인 시스템 토큰.
 * design/stitch_ai_vision_fridge_chef 의 Stitch 설정을 그대로 옮긴 것.
 */
/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "error-container": "#ffdad6",
        "surface-container-lowest": "#ffffff",
        "primary-container": "#1b5e20",
        "on-secondary": "#ffffff",
        "primary-fixed": "#acf4a4",
        "secondary-fixed": "#abf4ac",
        background: "#f6fbf3",
        "surface-container": "#ebefe8",
        "surface-variant": "#dfe4dc",
        "on-secondary-fixed": "#002107",
        "on-surface": "#181d18",
        "tertiary-fixed-dim": "#c2c9bb",
        "inverse-on-surface": "#eef2ea",
        "tertiary-fixed": "#dee5d6",
        "tertiary-container": "#4d5449",
        "outline-variant": "#c0c9bb",
        primary: "#00450d",
        "surface-bright": "#f6fbf3",
        "secondary-container": "#abf4ac",
        "on-primary-fixed": "#002203",
        "on-error": "#ffffff",
        "secondary-fixed-dim": "#90d792",
        "on-primary-container": "#90d689",
        "inverse-primary": "#91d78a",
        outline: "#717a6d",
        "on-background": "#181d18",
        "on-tertiary-fixed": "#171d14",
        "surface-dim": "#d7dbd4",
        "on-secondary-container": "#2e7238",
        "on-primary": "#ffffff",
        "on-tertiary": "#ffffff",
        "surface-tint": "#2a6b2c",
        secondary: "#286b33",
        "surface-container-highest": "#dfe4dc",
        "surface-container-high": "#e5eae2",
        "inverse-surface": "#2d322d",
        "on-error-container": "#93000a",
        "primary-fixed-dim": "#91d78a",
        "on-tertiary-container": "#c1c8ba",
        surface: "#f6fbf3",
        "surface-container-low": "#f1f5ed",
        "on-primary-fixed-variant": "#0c5216",
        "on-tertiary-fixed-variant": "#42493e",
        "on-surface-variant": "#41493e",
        tertiary: "#363d33",
        "on-secondary-fixed-variant": "#07521d",
        error: "#ba1a1a",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "margin-mobile": "16px",
        gutter: "24px",
        xl: "80px",
        md: "24px",
        lg: "48px",
        sm: "12px",
        "margin-desktop": "64px",
        xs: "4px",
        base: "8px",
      },
      fontFamily: {
        caption: ["Be Vietnam Pro", "sans-serif"],
        "headline-md": ["Plus Jakarta Sans", "sans-serif"],
        "body-lg": ["Be Vietnam Pro", "sans-serif"],
        "display-lg": ["Plus Jakarta Sans", "sans-serif"],
        "label-md": ["Be Vietnam Pro", "sans-serif"],
        "headline-lg-mobile": ["Plus Jakarta Sans", "sans-serif"],
        "body-md": ["Be Vietnam Pro", "sans-serif"],
        "headline-lg": ["Plus Jakarta Sans", "sans-serif"],
        sans: ["Be Vietnam Pro", "Pretendard", "system-ui", "sans-serif"],
      },
      fontSize: {
        caption: ["12px", { lineHeight: "16px", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "display-lg": [
          "48px",
          { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "label-md": [
          "14px",
          { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "600" },
        ],
        "headline-lg-mobile": ["28px", { lineHeight: "36px", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "600" }],
      },
    },
  },
  plugins: [forms],
};
